sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t kevincoakley/centos7-puppet centos/7/

script:
    - bash ./tests/centos_7.sh

after_script:
    - docker ps -a
    - docker logs kevincoakley/centos7-puppet