sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t kevincoakley/centos7-puppet:4.10.10 centos/7/4.10.10/

script:
    - bash ./tests/centos_7_4.10.10.sh

after_script:
    - docker ps -a
    - docker logs kevincoakley/centos7-puppet:4.10.10
